
name: Go CI + Docker + Security

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ===== Checkout =====
      - name: Checkout repository
        uses: actions/checkout@v4

      # ===== Go Build =====
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Go application
        working-directory: app
        run: |
          go mod tidy
          go build -o app

      # ===== Docker Build =====
      - name: Build Docker image
        run: |
          docker build \
            -t ghantotcon-cpu/cnd-project:ci \
            -f app/Dockerfile \
            .

      # ===== SBOM =====
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
          | sh -s -- -b /usr/local/bin

      - name: Generate SBOM
        run: |
          syft ghantotcon-cpu/cnd-project:ci -o spdx-json > sbom.json

      # ===== Security Scan (Trivy) =====
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -fsSL https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb stable main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan image for vulnerabilities
        run: |
          trivy image \
            --severity HIGH,CRITICAL \
            --exit-code 0 \
            ghantotcon-cpu/cnd-project:ci

