name: Go CI + Docker + Security + Cosign

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Go application
        working-directory: app
        run: |
          go mod tidy
          go build -o app

      - name: Build Docker image
        run: |
          docker build \
            -t ghantotcon-cpu/cnd-project:ci \
            -f app/Dockerfile \
            .
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" \
            --password-stdin

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
          | sh -s -- -b /usr/local/bin

      - name: Generate SBOM
        run: |
          syft ghantotcon-cpu/cnd-project:ci -o spdx-json > sbom.json

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
          | sudo sh -s -- -b /usr/local/bin

      - name: Scan image for vulnerabilities
        run: |
          trivy image \
            --severity HIGH,CRITICAL \
            --exit-code 0 \
            ghantotcon-cpu/cnd-project:ci

      - name: Install Cosign
        run: |
          curl -sSfL https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 \
          -o cosign
          chmod +x cosign
          sudo mv cosign /usr/local/bin/

      - name: Sign Docker image with Cosign (keyless)
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign sign ghantotcon-cpu/cnd-project:ci

